<!DOCTYPE html>
<html lang="en">
<head>
  <title>Homework Dropbox for Math ...</title>
  <meta charset="UTF-8" />
  <meta name="author" lang="en" content="Šarunas Burdulis" />
  <link rel="stylesheet" href="screen.css" type="text/css" />
  <link rel="icon" href="graecolatin_ico.png" type="image/png" />
</head>
<body>
<h1>Topics in ...</h1>
<h3>Math ..., Term Year</h3>
<h3>Prof. ...</h3>
<hr />
<h2>Homework Dropbox:</h2>
<p>
(100MB max.)<br />

<form action="upload_file.phtml" method="post" enctype="multipart/form-data">
<input type="file" name="file" id="file" />
<input type="hidden" name="MAX_FILE_SIZE" value="100000000" /> <input type="submit" name="submit" value="Submit" />
</form>
</p>

<p><em>Authenticated as 
<?php
    # REMOTE_USER as returned from Webauth
    echo $_SERVER['REMOTE_USER'] . '. ';
    # If Dan R., display a link to dropbox dir
    if ( $_SERVER['REMOTE_USER'] == 'Daniel N. Rockmore' || $_SERVER['REMOTE_USER'] == 'Sarunas Burdulis' ){
	echo '<a href="dropbox">View uploaded files.</a>';
    }
?>
</em></p>
<hr />
<a href="http://math.dartmouth.edu">Mathematics at Dartmouth</a>
</body>
</html> 

